In [35]:
import pandas as pd
df=pd.read_csv("/Users/Aneta/Desktop/Final_Project_Aneta/clean_dataset1.csv", header=0, sep=",")
df.head(4)

,Unnamed: 0,user,day_id,date,minute_id,image_directory,image_id,image_path,location,activity,...,weight,path_id,image_time_x,time,date_time,activity_new,day_of_week_name,time_hour,time_range,date_just
0,61388,u1,1,2015-02-23 00:00:00,425,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070647_1,/u1/2015-02-23/b00000000_21i6bq_20150223_07064...,Home,NaN,...,78,b00000000_21i6bq_20150223_070647e,7064.0,0 days 07:06:04.000000000,2015-02-23 07:06:04,NaN,NaN,7.0,morning,2015-02-23
1,61389,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070808_1,/u1/2015-02-23/b00000001_21i6bq_20150223_07080...,Home,NaN,...,78,b00000001_21i6bq_20150223_070808e,7080.0,0 days 07:08:00.000000000,2015-02-23 07:08:00,NaN,NaN,7.0,morning,2015-02-23
2,61390,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070809_2,/u1/2015-02-23/b00000002_21i6bq_20150223_07080...,Home,NaN,...,78,b00000002_21i6bq_20150223_070809e,7080.0,0 days 07:08:00.000000000,2015-02-23 07:08:00,NaN,NaN,7.0,morning,2015-02-23
3,61391,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070810_3,/u1/2015-02-23/b00000003_21i6bq_20150223_07081...,Home,NaN,...,78,b00000003_21i6bq_20150223_070810e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,NaN,NaN,7.0,morning,2015-02-23

In [36]:
df["location_code"]=df["location"]
df

,Unnamed: 0,user,day_id,date,minute_id,image_directory,image_id,image_path,location,activity,...,path_id,image_time_x,time,date_time,activity_new,day_of_week_name,time_hour,time_range,date_just,location_code
0,61388,u1,1,2015-02-23 00:00:00,425,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070647_1,/u1/2015-02-23/b00000000_21i6bq_20150223_07064...,Home,NaN,...,b00000000_21i6bq_20150223_070647e,7064.0,0 days 07:06:04.000000000,2015-02-23 07:06:04,NaN,NaN,7.0,morning,2015-02-23,Home
1,61389,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070808_1,/u1/2015-02-23/b00000001_21i6bq_20150223_07080...,Home,NaN,...,b00000001_21i6bq_20150223_070808e,7080.0,0 days 07:08:00.000000000,2015-02-23 07:08:00,NaN,NaN,7.0,morning,2015-02-23,Home
2,61390,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070809_2,/u1/2015-02-23/b00000002_21i6bq_20150223_07080...,Home,NaN,...,b00000002_21i6bq_20150223_070809e,7080.0,0 days 07:08:00.000000000,2015-02-23 07:08:00,NaN,NaN,7.0,morning,2015-02-23,Home
3,61391,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070810_3,/u1/2015-02-23/b00000003_21i6bq_20150223_07081...,Home,NaN,...,b00000003_21i6bq_20150223_070810e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,NaN,NaN,7.0,morning,2015-02-23,Home
4,61392,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070810_4,/u1/2015-02-23/b00000004_21i6bq_20150223_07081...,Home,NaN,...,b00000004_21i6bq_20150223_070810e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,NaN,NaN,7.0,morning,2015-02-23,Home
5,61393,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070811_5,/u1/2015-02-23/b00000005_21i6bq_20150223_07081...,Home,NaN,...,b00000005_21i6bq_20150223_070811e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,NaN,NaN,7.0,morning,2015-02-23,Home
6,61394,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070812_6,/u1/2015-02-23/b00000006_21i6bq_20150223_07081...,Home,NaN,...,b00000006_21i6bq_20150223_070812e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,mobile,Monday,7.0,morning,2015-02-23,Home
7,61395,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070813_7,/u1/2015-02-23/b00000007_21i6bq_20150223_07081...,Home,NaN,...,b00000007_21i6bq_20150223_070813e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,cooking,Monday,7.0,morning,2015-02-23,Home
8,61396,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070813_8,/u1/2015-02-23/b00000008_21i6bq_20150223_07081...,Home,NaN,...,b00000008_21i6bq_20150223_070813e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,cooking,Monday,7.0,morning,2015-02-23,Home
9,61397,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070814_9,/u1/2015-02-23/b00000009_21i6bq_20150223_07081...,Home,NaN,...,b00000009_21i6bq_20150223_070814e,7081.0,0 days 07:08:01.000000000,2015-02-23 07:08:01,cooking,Monday,7.0,morning,2015-02-23,Home
10,61398,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070822_10,/u1/2015-02-23/b00000010_21i6bq_20150223_07082...,Home,NaN,...,b00000010_21i6bq_20150223_070822e,7082.0,0 days 07:08:02.000000000,2015-02-23 07:08:02,cooking,Monday,7.0,morning,2015-02-23,Home
11,61399,u1,1,2015-02-23 00:00:00,427,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070859_11,/u1/2015-02-23/b00000011_21i6bq_20150223_07085...,Home,NaN,...,b00000011_21i6bq_20150223_070859e,7085.0,0 days 07:08:05.000000000,2015-02-23 07:08:05,cooking,Monday,7.0,morning,2015-02-23,Home
12,61400,u1,1,2015-02-23 00:00:00,428,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_070931_1,/u1/2015-02-23/b00000012_21i6bq_20150223_07093...,Home,NaN,...,b00000012_21i6bq_20150223_070931e,7093.0,0 days 07:09:03.000000000,2015-02-23 07:09:03,cooking,Monday,7.0,morning,2015-02-23,Home
13,61401,u1,1,2015-02-23 00:00:00,429,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071008_1,/u1/2015-02-23/b00000013_21i6bq_20150223_07100...,Home,NaN,...,b00000013_21i6bq_20150223_071008e,7100.0,0 days 07:10:00.000000000,2015-02-23 07:10:00,having drinks\meal alone,Monday,7.0,morning,2015-02-23,Home
14,61402,u1,1,2015-02-23 00:00:00,429,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071046_2,/u1/2015-02-23/b00000014_21i6bq_20150223_07104...,Home,NaN,...,b00000014_21i6bq_20150223_071046e,7104.0,0 days 07:10:04.000000000,2015-02-23 07:10:04,tv,Monday,7.0,morning,2015-02-23,Home
15,61403,u1,1,2015-02-23 00:00:00,430,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071119_1,/u1/2015-02-23/b00000015_21i6bq_20150223_07111...,Home,NaN,...,b00000015_21i6bq_20150223_071119e,7111.0,0 days 07:11:01.000000000,2015-02-23 07:11:01,tv,Monday,7.0,morning,2015-02-23,Home
16,61404,u1,1,2015-02-23 00:00:00,430,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071152_2,/u1/2015-02-23/b00000016_21i6bq_20150223_07115...,Home,NaN,...,b00000016_21i6bq_20150223_071152e,7115.0,0 days 07:11:05.000000000,2015-02-23 07:11:05,having drinks\meal alone,Monday,7.0,morning,2015-02-23,Home
17,61405,u1,1,2015-02-23 00:00:00,431,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071228_1,/u1/2015-02-23/b00000017_21i6bq_20150223_07122...,Home,NaN,...,b00000017_21i6bq_20150223_071228e,7122.0,0 days 07:12:02.000000000,2015-02-23 07:12:02,tv,Monday,7.0,morning,2015-02-23,Home
18,61406,u1,1,2015-02-23 00:00:00,432,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071305_1,/u1/2015-02-23/b00000018_21i6bq_20150223_07130...,Home,NaN,...,b00000018_21i6bq_20150223_071305e,7130.0,0 days 07:13:00.000000000,2015-02-23 07:13:00,tv,Monday,7.0,morning,2015-02-23,Home
19,61407,u1,1,2015-02-23 00:00:00,432,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071344_2,/u1/2015-02-23/b00000019_21i6bq_20150223_07134...,Home,NaN,...,b00000019_21i6bq_20150223_071344e,7134.0,0 days 07:13:04.000000000,2015-02-23 07:13:04,having drinks\meal alone,Monday,7.0,morning,2015-02-23,Home
20,61408,u1,1,2015-02-23 00:00:00,433,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071416_1,/u1/2015-02-23/b00000020_21i6bq_20150223_07141...,Home,NaN,...,b00000020_21i6bq_20150223_071416e,7141.0,0 days 07:14:01.000000000,2015-02-23 07:14:01,having drinks\meal alone,Monday,7.0,morning,2015-02-23,Home
21,61409,u1,1,2015-02-23 00:00:00,433,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071451_2,/u1/2015-02-23/b00000021_21i6bq_20150223_07145...,Home,NaN,...,b00000021_21i6bq_20150223_071451e,7145.0,0 days 07:14:05.000000000,2015-02-23 07:14:05,tv,Monday,7.0,morning,2015-02-23,Home
22,61410,u1,1,2015-02-23 00:00:00,434,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071528_1,/u1/2015-02-23/b00000022_21i6bq_20150223_07152...,Home,NaN,...,b00000022_21i6bq_20150223_071528e,7152.0,0 days 07:15:02.000000000,2015-02-23 07:15:02,tv,Monday,7.0,morning,2015-02-23,Home
23,61411,u1,1,2015-02-23 00:00:00,435,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071607_1,/u1/2015-02-23/b00000023_21i6bq_20150223_07160...,Home,NaN,...,b00000023_21i6bq_20150223_071607e,7160.0,0 days 07:16:00.000000000,2015-02-23 07:16:00,having drinks\meal alone,Monday,7.0,morning,2015-02-23,Home
24,61412,u1,1,2015-02-23 00:00:00,435,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071646_2,/u1/2015-02-23/b00000024_21i6bq_20150223_07164...,Home,NaN,...,b00000024_21i6bq_20150223_071646e,7164.0,0 days 07:16:04.000000000,2015-02-23 07:16:04,resting,Monday,7.0,morning,2015-02-23,Home
25,61413,u1,1,2015-02-23 00:00:00,436,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071723_1,/u1/2015-02-23/b00000025_21i6bq_20150223_07172...,Home,NaN,...,b00000025_21i6bq_20150223_071723e,7172.0,0 days 07:17:02.000000000,2015-02-23 07:17:02,resting,Monday,7.0,morning,2015-02-23,Home
26,61414,u1,1,2015-02-23 00:00:00,436,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071754_2,/u1/2015-02-23/b00000026_21i6bq_20150223_07175...,Home,NaN,...,b00000026_21i6bq_20150223_071754e,7175.0,0 days 07:17:05.000000000,2015-02-23 07:17:05,resting,Monday,7.0,morning,2015-02-23,Home
27,61415,u1,1,2015-02-23 00:00:00,437,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071835_1,/u1/2015-02-23/b00000027_21i6bq_20150223_07183...,Home,NaN,...,b00000027_21i6bq_20150223_071835e,7183.0,0 days 07:18:03.000000000,2015-02-23 07:18:03,resting,Monday,7.0,morning,2015-02-23,Home
28,61416,u1,1,2015-02-23 00:00:00,438,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071906_1,/u1/2015-02-23/b00000028_21i6bq_20150223_07190...,Home,NaN,...,b00000028_21i6bq_20150223_071906e,7190.0,0 days 07:19:00.000000000,2015-02-23 07:19:00,resting,Monday,7.0,morning,2015-02-23,Home
29,61417,u1,1,2015-02-23 00:00:00,438,NTCIR-Lifelog_images/u1/2015-02-23/,u1_2015-02-23_071937_2,/u1/2015-02-23/b00000029_21i6bq_20150223_07193...,Home,NaN,...,b00000029_21i6bq_20150223_071937e,7193.0,0 days 07:19:03.000000000,2015-02-23 07:19:03,resting,Monday,7.0,morning,2015-02-23,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87922,149310,u3,79,2015-08-03 00:00:00,113642,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220107_1,/u3/2015-08-03/b00001104_21i79q_20150803_22010...,NaN,NaN,...,b00001104_21i79q_20150803_220107e,22010.0,0 days 22:01:00.000000000,2015-08-03 22:01:00,NaN,NaN,22.0,evening,2015-08-03,NaN
87923,149311,u3,79,2015-08-03 00:00:00,113642,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220137_2,/u3/2015-08-03/b00001105_21i79q_20150803_22013...,NaN,NaN,...,b00001105_21i79q_20150803_220137e,22013.0,0 days 22:01:03.000000000,2015-08-03 22:01:03,NaN,NaN,22.0,evening,2015-08-03,NaN
87924,149312,u3,79,2015-08-03 00:00:00,113643,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220207_1,/u3/2015-08-03/b00001106_21i79q_20150803_22020...,NaN,NaN,...,b00001106_21i79q_20150803_220207e,22020.0,0 days 22:02:00.000000000,2015-08-03 22:02:00,NaN,NaN,22.0,evening,2015-08-03,NaN
87925,149313,u3,79,2015-08-03 00:00:00,113643,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220237_2,/u3/2015-08-03/b00001107_21i79q_20150803_22023...,NaN,NaN,...,b00001107_21i79q_20150803_220237e,22023.0,0 days 22:02:03.000000000,2015-08-03 22:02:03,NaN,NaN,22.0,evening,2015-08-03,NaN
87926,149314,u3,79,2015-08-03 00:00:00,113644,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220307_1,/u3/2015-08-03/b00001108_21i79q_20150803_22030...,NaN,NaN,...,b00001108_21i79q_20150803_220307e,22030.0,0 days 22:03:00.000000000,2015-08-03 22:03:00,NaN,NaN,22.0,evening,2015-08-03,NaN
87927,149315,u3,79,2015-08-03 00:00:00,113644,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220337_2,/u3/2015-08-03/b00001109_21i79q_20150803_22033...,NaN,NaN,...,b00001109_21i79q_20150803_220337e,22033.0,0 days 22:03:03.000000000,2015-08-03 22:03:03,NaN,NaN,22.0,evening,2015-08-03,NaN
87928,149316,u3,79,2015-08-03 00:00:00,113645,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220407_1,/u3/2015-08-03/b00001110_21i79q_20150803_22040...,NaN,NaN,...,b00001110_21i79q_20150803_220407e,22040.0,0 days 22:04:00.000000000,2015-08-03 22:04:00,NaN,NaN,22.0,evening,2015-08-03,NaN
87929,149317,u3,79,2015-08-03 00:00:00,113645,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220447_2,/u3/2015-08-03/b00001111_21i79q_20150803_22044...,NaN,NaN,...,b00001111_21i79q_20150803_220447e,22044.0,0 days 22:04:04.000000000,2015-08-03 22:04:04,NaN,NaN,22.0,evening,2015-08-03,NaN
87930,149318,u3,79,2015-08-03 00:00:00,113646,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220517_1,/u3/2015-08-03/b00001112_21i79q_20150803_22051...,NaN,NaN,...,b00001112_21i79q_20150803_220517e,22051.0,0 days 22:05:01.000000000,2015-08-03 22:05:01,NaN,NaN,22.0,evening,2015-08-03,NaN
87931,149319,u3,79,2015-08-03 00:00:00,113646,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220547_2,/u3/2015-08-03/b00001113_21i79q_20150803_22054...,NaN,NaN,...,b00001113_21i79q_20150803_220547e,22054.0,0 days 22:05:04.000000000,2015-08-03 22:05:04,NaN,NaN,22.0,evening,2015-08-03,NaN
87932,149320,u3,79,2015-08-03 00:00:00,113647,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220617_1,/u3/2015-08-03/b00001114_21i79q_20150803_22061...,NaN,NaN,...,b00001114_21i79q_20150803_220617e,22061.0,0 days 22:06:01.000000000,2015-08-03 22:06:01,NaN,NaN,22.0,evening,2015-08-03,NaN
87933,149321,u3,79,2015-08-03 00:00:00,113647,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220647_2,/u3/2015-08-03/b00001115_21i79q_20150803_22064...,NaN,NaN,...,b00001115_21i79q_20150803_220647e,22064.0,0 days 22:06:04.000000000,2015-08-03 22:06:04,NaN,NaN,22.0,evening,2015-08-03,NaN
87934,149322,u3,79,2015-08-03 00:00:00,113648,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220717_1,/u3/2015-08-03/b00001116_21i79q_20150803_22071...,NaN,NaN,...,b00001116_21i79q_20150803_220717e,22071.0,0 days 22:07:01.000000000,2015-08-03 22:07:01,NaN,NaN,22.0,evening,2015-08-03,NaN
87935,149323,u3,79,2015-08-03 00:00:00,113648,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220747_2,/u3/2015-08-03/b00001117_21i79q_20150803_22074...,NaN,NaN,...,b00001117_21i79q_20150803_220747e,22074.0,0 days 22:07:04.000000000,2015-08-03 22:07:04,NaN,NaN,22.0,evening,2015-08-03,NaN
87936,149324,u3,79,2015-08-03 00:00:00,113649,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220817_1,/u3/2015-08-03/b00001118_21i79q_20150803_22081...,NaN,NaN,...,b00001118_21i79q_20150803_220817e,22081.0,0 days 22:08:01.000000000,2015-08-03 22:08:01,NaN,NaN,22.0,evening,2015-08-03,NaN
87937,149325,u3,79,2015-08-03 00:00:00,113649,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220847_2,/u3/2015-08-03/b00001119_21i79q_20150803_22084...,NaN,NaN,...,b00001119_21i79q_20150803_220847e,22084.0,0 days 22:08:04.000000000,2015-08-03 22:08:04,NaN,NaN,22.0,evening,2015-08-03,NaN
87938,149326,u3,79,2015-08-03 00:00:00,113650,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220927_1,/u3/2015-08-03/b00001120_21i79q_20150803_22092...,NaN,NaN,...,b00001120_21i79q_20150803_220927e,22092.0,0 days 22:09:02.000000000,2015-08-03 22:09:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87939,149327,u3,79,2015-08-03 00:00:00,113650,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_220957_2,/u3/2015-08-03/b00001121_21i79q_20150803_22095...,NaN,NaN,...,b00001121_21i79q_20150803_220957e,22095.0,0 days 22:09:05.000000000,2015-08-03 22:09:05,NaN,NaN,22.0,evening,2015-08-03,NaN
87940,149328,u3,79,2015-08-03 00:00:00,113651,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221027_1,/u3/2015-08-03/b00001122_21i79q_20150803_22102...,NaN,NaN,...,b00001122_21i79q_20150803_221027e,22102.0,0 days 22:10:02.000000000,2015-08-03 22:10:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87941,149329,u3,79,2015-08-03 00:00:00,113651,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221058_2,/u3/2015-08-03/b00001123_21i79q_20150803_22105...,NaN,NaN,...,b00001123_21i79q_20150803_221058e,22105.0,0 days 22:10:05.000000000,2015-08-03 22:10:05,NaN,NaN,22.0,evening,2015-08-03,NaN
87942,149330,u3,79,2015-08-03 00:00:00,113652,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221127_1,/u3/2015-08-03/b00001124_21i79q_20150803_22112...,NaN,NaN,...,b00001124_21i79q_20150803_221127e,22112.0,0 days 22:11:02.000000000,2015-08-03 22:11:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87943,149331,u3,79,2015-08-03 00:00:00,113652,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221157_2,/u3/2015-08-03/b00001125_21i79q_20150803_22115...,NaN,NaN,...,b00001125_21i79q_20150803_221157e,22115.0,0 days 22:11:05.000000000,2015-08-03 22:11:05,NaN,NaN,22.0,evening,2015-08-03,NaN
87944,149332,u3,79,2015-08-03 00:00:00,113653,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221227_1,/u3/2015-08-03/b00001126_21i79q_20150803_22122...,NaN,NaN,...,b00001126_21i79q_20150803_221227e,22122.0,0 days 22:12:02.000000000,2015-08-03 22:12:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87945,149333,u3,79,2015-08-03 00:00:00,113653,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221257_2,/u3/2015-08-03/b00001127_21i79q_20150803_22125...,NaN,NaN,...,b00001127_21i79q_20150803_221257e,22125.0,0 days 22:12:05.000000000,2015-08-03 22:12:05,NaN,NaN,22.0,evening,2015-08-03,NaN
87946,149334,u3,79,2015-08-03 00:00:00,113654,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221329_1,/u3/2015-08-03/b00001128_21i79q_20150803_22132...,NaN,NaN,...,b00001128_21i79q_20150803_221329e,22132.0,0 days 22:13:02.000000000,2015-08-03 22:13:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87947,149335,u3,79,2015-08-03 00:00:00,113654,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221359_2,/u3/2015-08-03/b00001129_21i79q_20150803_22135...,NaN,NaN,...,b00001129_21i79q_20150803_221359e,22135.0,0 days 22:13:05.000000000,2015-08-03 22:13:05,NaN,NaN,22.0,evening,2015-08-03,NaN
87948,149336,u3,79,2015-08-03 00:00:00,113655,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221429_1,/u3/2015-08-03/b00001130_21i79q_20150803_22142...,NaN,NaN,...,b00001130_21i79q_20150803_221429e,22142.0,0 days 22:14:02.000000000,2015-08-03 22:14:02,NaN,NaN,22.0,evening,2015-08-03,NaN
87949,149337,u3,79,2015-08-03 00:00:00,113656,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221505_1,/u3/2015-08-03/b00001131_21i79q_20150803_22150...,NaN,NaN,...,b00001131_21i79q_20150803_221505e,22150.0,0 days 22:15:00.000000000,2015-08-03 22:15:00,NaN,NaN,22.0,evening,2015-08-03,NaN
87950,149338,u3,79,2015-08-03 00:00:00,113656,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221535_2,/u3/2015-08-03/b00001132_21i79q_20150803_22153...,NaN,NaN,...,b00001132_21i79q_20150803_221535e,22153.0,0 days 22:15:03.000000000,2015-08-03 22:15:03,NaN,NaN,22.0,evening,2015-08-03,NaN
87951,149339,u3,79,2015-08-03 00:00:00,113657,NTCIR-Lifelog_images/u3/2015-08-03/,u3_2015-08-03_221618_1,/u3/2015-08-03/b00001133_21i79q_20150803_22161...,NaN,NaN,...,b00001133_21i79q_20150803_221618e,22161.0,0 days 22:16:01.000000000,2015-08-03 22:16:01,NaN,NaN,22.0,evening,2015-08-03,NaN

In [55]:
location_code=pd.read_csv("locations.csv", sep=";", index_col=0, header=0)
location_code["Log_lat"]=location_code["Log_lat"].astype(str)

l=[]
for index, row in location_code.iterrows():
    x="{"+str(row["locations"])+"','"+str(row["Log_lat"])+"'}"
    l.append(x)

l

["{'Home','53.349805, -6.26031'}",
 "{'nan','nan'}",
 "{'Work','53.349805, -6.26031'}",
 "{'Place in Grattan Lodge','53.401313, -6.166292'}",
 "{'Verbena Avenue','53.389244, -6.146647'}",
 "{'Dublin City University (DCU)','53.385100, -6.256615'}",
 "{'Science Gallery Caf\x8e','53.344264, -6.250179'}",
 "{'The Helix','53.386547, -6.258775'}",
 "{'DCU School of Nursing','53.386057, -6.254740\r\r'}",
 "{'Thunder Road Caf\x8e','53.345778, -6.261113'}",
 "{'The Westin','53.345825, -6.258249'}",
 "{'Brown Thomas','53.342513, -6.259910'}",
 "{'Place in Saint Anne's Park','53.371269, -6.179852'}",
 "{'Place in Rose Garden','53.353438, -6.300275'}",
 "{'Costa Coffee','53.343643, -6.248991'}",
 "{'Starbucks','53.350775, -6.239378'}",
 "{'Dunnes Stores','53.340639, -6.260792'}",
 "{'Dublin Airport (DUB) - Aerfort Bhaile \xe7tha Cliath','53.426454, -6.250285'}",
 "{'Bayside','53.387376, -6.143131'}",
 "{'Lidl','53.357538, -6.221120'}",
 "{'Place in Taney Civil Parish','53.291669, -6.237823'}",
 "{'O'Brien Centre for Science','53.308306, -6.223424'}",
 "{'Howth Junction Business Centre','53.390910, -6.153724'}",
 "{'Place in Dublin City University','53.385056, -6.256948'}",
 "{'Hilan Korean & Chinese Restaurant','53.348651, -6.267988'}",
 "{'Place in Dublin 9','53.337347, -6.253736'}",
 "{'Place in Balgriffin','53.409397, -6.170420'}",
 "{'Dublin Airport T2 Car Park','53.428519, -6.240129'}",
 "{'Place in Dardistown','53.412457, -6.237136'}",
 "{'Place in Greater Manchester','53.481562, -2.250377'}",
 "{'Car Rental Village','53.365687, -2.262970'}",
 "{'McDonald's','53.380190, -2.260604'}",
 "{'Sheffield University - Portobello Centre','53.381122, -1.481755'}",
 "{'Novotel','53.476944, -2.241356'}",
 "{'Sheffield Tap','53.378805, -1.462394'}",
 "{'Caf\x8e Rouge','53.379364, -1.469254'}",
 "{'The Antiques Emporium','54.335482, -2.746799'}",
 "{'Kinder Lodge','53.378422, -1.946675'}",
 "{'Devonshire Arms','53.392822, -2.025521'}",
 "{'Waterstones','53.481718, -2.247106'}",
 "{'Manchester International Airport (MAN)','53.358803, -2.272805'}",
 "{'Web Summit HQ','53.309277, -6.259983'}",
 "{'Pavilions Shopping Centre','53.454299, -6.218796\r\r'}",
 "{'Waterside','53.451859, -6.198626'}",
 "{'Eddie Rocket's','53.333084, -6.243449'}",
 "{'Homebase','53.328449, -6.341741'}",
 "{'Place in Dublin 15','53.378111, -6.326886'}",
 "{'Power City','53.388037, -6.298631'}",
 "{'Rathdown Park','53.305623, -6.288385'}",
 "{'Place in St. Mary's Enniscorthy','52.497738, -6.571991'}",
 "{'Caim Church','52.511733, -6.673646'}",
 "{'The Sisters Home','53.426442, -6.249302'}",
 "{'Gate 212','53.426442, -6.249302'}",
 "{'London City Airport (LCY)','51.504897, 0.049293'}",
 "{'Place in London City Airport','Place in London City Airport'}",
 "{'Tenter Street Apartment','51.513161, -0.071069'}",
 "{'Place in Butler's Wharf','51.503933, -0.074281'}",
 "{'Grange Tower Bridge Hotel','51.511605, -0.071916'}",
 "{'Place in Northside Shopping Centre','53.395951, -6.213138'}",
 "{'Gate 303','53.426442, -6.249302'}",
 "{'Place in Frankfurt am Main','50.118232, 8.674961'}",
 "{'Frankfurt Airport (FRA)','50.037939, 8.561926'}",
 "{'Gate Z66','31.144445, 121.808337'}",
 "{'Place in ?? Shanghai','31.374353, 121.497520'}",
 "{'Modern Universe Business Plaza','31.217113, 121.417470'}",
 "{'DCU Sports Complex','53.384710, -6.259239'}",
 "{'Place in Prospect Square','53.369235, -6.271626'}",
 "{'Place in Dublin 7','53.361526, -6.291717'}",
 "{'Bust Stop No 44','53.289996, -6.266278'}",
 "{'Tesco','53.289438, -6.267577'}",
 "{'Place in Dublin 1','53.353906, -6.254527'}",
 "{'DCU School of Computing','53.385056, -6.256820'}",
 "{'DCU Restaurant','53.384979, -6.255500'}",
 "{'Chilli Banana','53.372351, -6.252368'}",
 "{'Hampstead Park','53.379404, -6.263569'}",
 "{'Place in Temple Bar','53.345771, -6.262841'}",
 "{'Ulster Bank','53.344138, -6.260594'}",
 "{'The Hub','53.385210, -6.258556'}",
 "{'Dublin Airport (DUB)','53.426442, -6.250382'}",
 "{'Place in ??? / Chaoyang','39.916627, 116.455496'}",
 "{'Place in ??? (Beijing)','39.916627, 116.455496'}",
 "{'Place in ??','39.916627, 116.455496'}",
 "{'Place in ??? (Yong He Gong Lama Temple)','39.947647, 116.417548'}",
 "{'Place in ????','39.916627, 116.455496'}",
 "{'Place in ?????','39.916627, 116.455496'}",
 "{'Starbucks ???','39.916627, 116.455496'}",
 "{'??? McDonald's','39.916627, 116.455496'}",
 "{'Sosiaali - ja terveystoimi','60.181585, 24.947012'}",
 "{'Kauppatori','60.167655, 24.954010'}",
 "{'K-supermarket','60.171272, 24.948514'}",
 "{'Pys\x8akki 828','60.402096, 25.027550'}",
 "{'Ravintola Tower','67.604396, 24.153497'}",
 "{'Tiia koti','60.169871, 24.938477'}",
 "{'Place in Aviapoliksen suuralue','60.169871, 24.938477'}",
 "{'Place in APN 1','60.169871, 24.938477'}",
 "{'Helsinki railway station','60.169871, 24.938477'}",
 "{'Place in Kluuvi','60.168964, 24.947525'}",
 "{'Pub Varpu','60.169871, 24.938477'}",
 "{'Place in Ullanlinna','60.160419, 24.950412'}",
 "{'Mulhuddart Community Centre','53.405148, -6.393948'}",
 "{'Razor's Barber Shop','53.486829, -6.149580'}",
 "{'Blanchardstown / Baile Bhlains\x8eir','53.385268, -6.375847'}",
 "{'Tesco Express','53.382688, -6.381512'}",
 "{'Under Ildl','nan'}",
 "{'Bus\x87ras','53.349889, -6.252032'}",
 "{'Athlone Town Centre','53.424029, -7.936322'}",
 "{'Moate','53.395043, -7.718630'}",
 "{'Place in Dublin 11','53.389807, -6.292911'}",
 "{'Place in Rotunda Maternity Hospital','53.353098, -6.263189'}",
 "{'Woolshed Baa & Grill','53.350362, -6.266863'}",
 "{'Reed Specialist Recruitment','53.341763, -6.259721'}",
 "{'Dublin Bus','53.343988, -6.268996'}",
 "{'Citizens Information','53.345839, -6.252680'}",
 "{'40D Bus Stop','53.290025, -6.266488'}",
 "{'Dublin Bus Stop No. 4522','53.290025, -6.266488'}",
 "{'Citywest Shopping Centre','53.282509, -6.422597'}",
 "{'Uniphar','53.293132, -6.415556'}",
 "{'Terminal 1','53.422521, -6.239523'}",
 "{'Butchery','53.350213, -6.258076'}",
 "{'Finglas Leisure Centre','53.390208, -6.304685'}",
 "{'Bus Stop 1624','53.389867, -6.306590'}"]

In [63]:
x=df["location_code"].replace({'Home','53.349805, -6.26031'},
 {'nan','nan'},
 {'Work','53.349805, -6.26031'},
 {'Place in Grattan Lodge','53.401313, -6.166292'},
 {'Verbena Avenue','53.389244, -6.146647'},
 {'Dublin City University (DCU)','53.385100, -6.256615'},
 {'Science Gallery Caf\x8e','53.344264, -6.250179'},
 {'The Helix','53.386547, -6.258775'},
 {'DCU School of Nursing','53.386057, -6.254740\r\r'},
 {'Thunder Road Caf\x8e','53.345778, -6.261113'},
 {'The Westin','53.345825, -6.258249'},
 {'Brown Thomas','53.342513, -6.259910'},
 {"Place in Saint Anne's Park",'53.371269, -6.179852'},
 {'Place in Rose Garden','53.353438, -6.300275'},
 {'Costa Coffee','53.343643, -6.248991'},
 {'Starbucks','53.350775, -6.239378'},
 {'Dunnes Stores','53.340639, -6.260792'},
 {'Dublin Airport (DUB) - Aerfort Bhaile \xe7tha Cliath','53.426454, -6.250285'},
 {'Bayside','53.387376, -6.143131'},
 {'Lidl','53.357538, -6.221120'},
 {'Place in Taney Civil Parish','53.291669, -6.237823'},
 {"O'Brien Centre for Science",'53.308306, -6.223424'},
 {'Howth Junction Business Centre','53.390910, -6.153724'},
 {'Place in Dublin City University','53.385056, -6.256948'},
 {'Hilan Korean & Chinese Restaurant','53.348651, -6.267988'},
 {'Place in Dublin 9','53.337347, -6.253736'},
 {'Place in Balgriffin','53.409397, -6.170420'},
 {'Dublin Airport T2 Car Park','53.428519, -6.240129'},
 {'Place in Dardistown','53.412457, -6.237136'},
 {'Place in Greater Manchester','53.481562, -2.250377'},
 {'Car Rental Village','53.365687, -2.262970'},
 {"McDonald's",'53.380190, -2.260604'},
 {'Sheffield University - Portobello Centre','53.381122, -1.481755'},
 {'Novotel','53.476944, -2.241356'},
 {'Sheffield Tap','53.378805, -1.462394'},
 {'Caf\x8e Rouge','53.379364, -1.469254'},
 {'The Antiques Emporium','54.335482, -2.746799'},
 {'Kinder Lodge','53.378422, -1.946675'},
 {'Devonshire Arms','53.392822, -2.025521'},
 {'Waterstones','53.481718, -2.247106'},
 {'Manchester International Airport (MAN)','53.358803, -2.272805'},
 {'Web Summit HQ','53.309277, -6.259983'},
 {'Pavilions Shopping Centre','53.454299, -6.218796\r\r'},
 {'Waterside','53.451859, -6.198626'},
 {"Eddie Rocket's",'53.333084, -6.243449'},
 {'Homebase','53.328449, -6.341741'},
 {'Place in Dublin 15','53.378111, -6.326886'},
 {'Power City','53.388037, -6.298631'},
 {'Rathdown Park','53.305623, -6.288385'},
 {"Place in St. Mary's Enniscorthy",'52.497738, -6.571991'},
 {'Caim Church','52.511733, -6.673646'},
 {'The Sisters Home','53.426442, -6.249302'},
 {'Gate 212','53.426442, -6.249302'},
 {'London City Airport (LCY)','51.504897, 0.049293'},
 {'Place in London City Airport','Place in London City Airport'},
 {'Tenter Street Apartment','51.513161, -0.071069'},
 {"Place in Butler's Wharf",'51.503933, -0.074281'},
 {'Grange Tower Bridge Hotel','51.511605, -0.071916'},
 {'Place in Northside Shopping Centre','53.395951, -6.213138'},
 {'Gate 303','53.426442, -6.249302'},
 {'Place in Frankfurt am Main','50.118232, 8.674961'},
 {'Frankfurt Airport (FRA)','50.037939, 8.561926'},
 {'Gate Z66','31.144445, 121.808337'},
 {'Place in ?? Shanghai','31.374353, 121.497520'},
 {'Modern Universe Business Plaza','31.217113, 121.417470'},
 {'DCU Sports Complex','53.384710, -6.259239'},
 {'Place in Prospect Square','53.369235, -6.271626'},
 {'Place in Dublin 7','53.361526, -6.291717'},
 {'Bust Stop No 44','53.289996, -6.266278'},
 {'Tesco','53.289438, -6.267577'},
 {'Place in Dublin 1','53.353906, -6.254527'},
 {'DCU School of Computing','53.385056, -6.256820'},
 {'DCU Restaurant','53.384979, -6.255500'},
 {'Chilli Banana','53.372351, -6.252368'},
 {'Hampstead Park','53.379404, -6.263569'},
 {'Place in Temple Bar','53.345771, -6.262841'},
 {'Ulster Bank','53.344138, -6.260594'},
 {'The Hub','53.385210, -6.258556'},
 {'Dublin Airport (DUB)','53.426442, -6.250382'},
 {'Place in ??? / Chaoyang','39.916627, 116.455496'},
 {'Place in ??? (Beijing)','39.916627, 116.455496'},
 {'Place in ??','39.916627, 116.455496'},
 {'Place in ??? (Yong He Gong Lama Temple)','39.947647, 116.417548'},
 {'Place in ????','39.916627, 116.455496'},
 {'Place in ?????','39.916627, 116.455496'},
 {'Starbucks ???','39.916627, 116.455496'},
 {"??? McDonald's",'39.916627, 116.455496'},
 {'Sosiaali - ja terveystoimi','60.181585, 24.947012'},
 {'Kauppatori','60.167655, 24.954010'},
 {'K-supermarket','60.171272, 24.948514'},
 {'Pys\x8akki 828','60.402096, 25.027550'},
 {'Ravintola Tower','67.604396, 24.153497'},
 {'Tiia koti','60.169871, 24.938477'},
 {'Place in Aviapoliksen suuralue','60.169871, 24.938477'},
 {'Place in APN 1','60.169871, 24.938477'},
 {'Helsinki railway station','60.169871, 24.938477'},
 {'Place in Kluuvi','60.168964, 24.947525'},
 {'Pub Varpu','60.169871, 24.938477'},
 {'Place in Ullanlinna','60.160419, 24.950412'},
 {'Mulhuddart Community Centre','53.405148, -6.393948'},
 {"Razor's Barber Shop",'53.486829, -6.149580'},
 {'Blanchardstown / Baile Bhlains\x8eir','53.385268, -6.375847'},
 {'Tesco Express','53.382688, -6.381512'},
 {'Under Ildl','nan'},
 {'Bus\x87ras','53.349889, -6.252032'},
 {'Athlone Town Centre','53.424029, -7.936322'},
 {'Moate','53.395043, -7.718630'},
 {'Place in Dublin 11','53.389807, -6.292911'},
 {'Place in Rotunda Maternity Hospital','53.353098, -6.263189'},
 {'Woolshed Baa & Grill','53.350362, -6.266863'},
 {'Reed Specialist Recruitment','53.341763, -6.259721'},
 {'Dublin Bus','53.343988, -6.268996'},
 {'Citizens Information','53.345839, -6.252680'},
 {'40D Bus Stop','53.290025, -6.266488'},
 {'Dublin Bus Stop No. 4522','53.290025, -6.266488'},
 {'Citywest Shopping Centre','53.282509, -6.422597'},
 {'Uniphar','53.293132, -6.415556'},
 {'Terminal 1','53.422521, -6.239523'},
 {'Butchery','53.350213, -6.258076'},
 {'Finglas Leisure Centre','53.390208, -6.304685'},
 {'Bus Stop 1624','53.389867, -6.306590'})

TypeError: replace() takes at most 8 arguments (122 given)

In [21]:
locs

array([['Home', '53.349805, -6.26031'],
       [nan, nan],
       ['Work', '53.349805, -6.26031'],
       ['Place in Grattan Lodge', '53.401313, -6.166292'],
       ['Verbena Avenue', '53.389244, -6.146647'],
       ['Dublin City University (DCU)', '53.385100, -6.256615'],
       ['Science Gallery Caf\x8e', '53.344264, -6.250179'],
       ['The Helix', '53.386547, -6.258775'],
       ['DCU School of Nursing', '53.386057, -6.254740\r\r'],
       ['Thunder Road Caf\x8e', '53.345778, -6.261113'],
       ['The Westin', '53.345825, -6.258249'],
       ['Brown Thomas', '53.342513, -6.259910'],
       ["Place in Saint Anne's Park", '53.371269, -6.179852'],
       ['Place in Rose Garden', '53.353438, -6.300275'],
       ['Costa Coffee', '53.343643, -6.248991'],
       ['Starbucks', '53.350775, -6.239378'],
       ['Dunnes Stores', '53.340639, -6.260792'],
       ['Dublin Airport (DUB) - Aerfort Bhaile \xe7tha Cliath',
        '53.426454, -6.250285'],
       ['Bayside', '53.387376, -6.143131'],
       ['Lidl', '53.357538, -6.221120'],
       ['Place in Taney Civil Parish', '53.291669, -6.237823'],
       ["O'Brien Centre for Science", '53.308306, -6.223424'],
       ['Howth Junction Business Centre', '53.390910, -6.153724'],
       ['Place in Dublin City University', '53.385056, -6.256948'],
       ['Hilan Korean & Chinese Restaurant', '53.348651, -6.267988'],
       ['Place in Dublin 9', '53.337347, -6.253736'],
       ['Place in Balgriffin', '53.409397, -6.170420'],
       ['Dublin Airport T2 Car Park', '53.428519, -6.240129'],
       ['Place in Dardistown', '53.412457, -6.237136'],
       ['Place in Greater Manchester', '53.481562, -2.250377'],
       ['Car Rental Village', '53.365687, -2.262970'],
       ["McDonald's", '53.380190, -2.260604'],
       ['Sheffield University - Portobello Centre', '53.381122, -1.481755'],
       ['Novotel', '53.476944, -2.241356'],
       ['Sheffield Tap', '53.378805, -1.462394'],
       ['Caf\x8e Rouge', '53.379364, -1.469254'],
       ['The Antiques Emporium', '54.335482, -2.746799'],
       ['Kinder Lodge', '53.378422, -1.946675'],
       ['Devonshire Arms', '53.392822, -2.025521'],
       ['Waterstones', '53.481718, -2.247106'],
       ['Manchester International Airport (MAN)', '53.358803, -2.272805'],
       ['Web Summit HQ', '53.309277, -6.259983'],
       ['Pavilions Shopping Centre', '53.454299, -6.218796\r\r'],
       ['Waterside', '53.451859, -6.198626'],
       ["Eddie Rocket's", '53.333084, -6.243449'],
       ['Homebase', '53.328449, -6.341741'],
       ['Place in Dublin 15', '53.378111, -6.326886'],
       ['Power City', '53.388037, -6.298631'],
       ['Rathdown Park', '53.305623, -6.288385'],
       ["Place in St. Mary's Enniscorthy", '52.497738, -6.571991'],
       ['Caim Church', '52.511733, -6.673646'],
       ['The Sisters Home', '53.426442, -6.249302'],
       ['Gate 212', '53.426442, -6.249302'],
       ['London City Airport (LCY)', '51.504897, 0.049293'],
       ['Place in London City Airport', 'Place in London City Airport'],
       ['Tenter Street Apartment', '51.513161, -0.071069'],
       ["Place in Butler's Wharf", '51.503933, -0.074281'],
       ['Grange Tower Bridge Hotel', '51.511605, -0.071916'],
       ['Place in Northside Shopping Centre', '53.395951, -6.213138'],
       ['Gate 303', '53.426442, -6.249302'],
       ['Place in Frankfurt am Main', '50.118232, 8.674961'],
       ['Frankfurt Airport (FRA)', '50.037939, 8.561926'],
       ['Gate Z66', '31.144445, 121.808337'],
       ['Place in ?? Shanghai', '31.374353, 121.497520'],
       ['Modern Universe Business Plaza', '31.217113, 121.417470'],
       ['DCU Sports Complex', '53.384710, -6.259239'],
       ['Place in Prospect Square', '53.369235, -6.271626'],
       ['Place in Dublin 7', '53.361526, -6.291717'],
       ['Bust Stop No 44', '53.289996, -6.266278'],
       ['Tesco', '53.289438, -6.267577'],
       ['Place in Dublin 1', '53.353906, -6.254527'],
       ['DCU School of Computing', '53.385056, -6.256820'],
       ['DCU Restaurant', '53.384979, -6.255500'],
       ['Chilli Banana', '53.372351, -6.252368'],
       ['Hampstead Park', '53.379404, -6.263569'],
       ['Place in Temple Bar', '53.345771, -6.262841'],
       ['Ulster Bank', '53.344138, -6.260594'],
       ['The Hub', '53.385210, -6.258556'],
       ['Dublin Airport (DUB)', '53.426442, -6.250382'],
       ['Place in ??? / Chaoyang', '39.916627, 116.455496'],
       ['Place in ??? (Beijing)', '39.916627, 116.455496'],
       ['Place in ??', '39.916627, 116.455496'],
       ['Place in ??? (Yong He Gong Lama Temple)', '39.947647, 116.417548'],
       ['Place in ????', '39.916627, 116.455496'],
       ['Place in ?????', '39.916627, 116.455496'],
       ['Starbucks ???', '39.916627, 116.455496'],
       ["??? McDonald's", '39.916627, 116.455496'],
       ['Sosiaali - ja terveystoimi', '60.181585, 24.947012'],
       ['Kauppatori', '60.167655, 24.954010'],
       ['K-supermarket', '60.171272, 24.948514'],
       ['Pys\x8akki 828', '60.402096, 25.027550'],
       ['Ravintola Tower', '67.604396, 24.153497'],
       ['Tiia koti', '60.169871, 24.938477'],
       ['Place in Aviapoliksen suuralue', '60.169871, 24.938477'],
       ['Place in APN 1', '60.169871, 24.938477'],
       ['Helsinki railway station', '60.169871, 24.938477'],
       ['Place in Kluuvi', '60.168964, 24.947525'],
       ['Pub Varpu', '60.169871, 24.938477'],
       ['Place in Ullanlinna', '60.160419, 24.950412'],
       ['Mulhuddart Community Centre', '53.405148, -6.393948'],
       ["Razor's Barber Shop", '53.486829, -6.149580'],
       ['Blanchardstown / Baile Bhlains\x8eir', '53.385268, -6.375847'],
       ['Tesco Express', '53.382688, -6.381512'],
       ['Under Ildl', nan],
       ['Bus\x87ras', '53.349889, -6.252032'],
       ['Athlone Town Centre', '53.424029, -7.936322'],
       ['Moate', '53.395043, -7.718630'],
       ['Place in Dublin 11', '53.389807, -6.292911'],
       ['Place in Rotunda Maternity Hospital', '53.353098, -6.263189'],
       ['Woolshed Baa & Grill', '53.350362, -6.266863'],
       ['Reed Specialist Recruitment', '53.341763, -6.259721'],
       ['Dublin Bus', '53.343988, -6.268996'],
       ['Citizens Information', '53.345839, -6.252680'],
       ['40D Bus Stop', '53.290025, -6.266488'],
       ['Dublin Bus Stop No. 4522', '53.290025, -6.266488'],
       ['Citywest Shopping Centre', '53.282509, -6.422597'],
       ['Uniphar', '53.293132, -6.415556'],
       ['Terminal 1', '53.422521, -6.239523'],
       ['Butchery', '53.350213, -6.258076'],
       ['Finglas Leisure Centre', '53.390208, -6.304685'],
       ['Bus Stop 1624', '53.389867, -6.306590']], dtype=object)

In [10]:
len(df['location'].unique())

121

In [2]:
from geopy.geocoders import Nominatim
# LET'S TRY TO PUT THE LOCATIONS ON A MAP:

geolocator = Nominatim()
locations = df['location'].unique() #list of all locations for user 1

latitude = []
longitude = []
locations=locations[2:]
locations_found=[]

for loc in locations:
    print(loc)
    try:
        location = geolocator.geocode(unicode(loc, "utf-8"))
        latitude.append(location.latitude)
        longitude.append(location.longitude)
        locations_found.append(loc)
    except:
        print('not found')

Work
Place in Grattan Lodge
Verbena Avenue
Dublin City University (DCU)
Science Gallery Cafï¿½
not found
The Helix
DCU School of Nursing
not found
Thunder Road Cafï¿½
not found
The Westin
Brown Thomas
Place in Saint Anne's Park
not found
Place in Rose Garden
Costa Coffee
Starbucks
Dunnes Stores
Dublin Airport (DUB) - Aerfort Bhaile ï¿½tha Cliath
not found
Bayside
Lidl
Place in Taney Civil Parish
not found
O'Brien Centre for Science
Howth Junction Business Centre
not found
Place in Dublin City University
not found
Hilan Korean & Chinese Restaurant
not found
Place in Dublin 9
Place in Balgriffin
not found
Dublin Airport T2 Car Park
not found
Place in Dardistown
not found
Place in Greater Manchester
Car Rental Village
McDonald's
Sheffield University - Portobello Centre
not found
Novotel
Sheffield Tap
Cafï¿½ Rouge
not found
The Antiques Emporium
Kinder Lodge
Devonshire Arms
Waterstones
Manchester International Airport (MAN)
not found
Web Summit HQ
not found
Pavilions Shopping Centre
Waterside
Eddie Rocket's
Homebase
Place in Dublin 15
not found
Power City
Rathdown Park
Place in St. Mary's Enniscorthy
Caim Church
The Sisters Home
Gate 212
London City Airport (LCY)
Place in London City Airport
not found
Tenter Street Apartment
not found
Place in Butler's Wharf
Grange Tower Bridge Hotel
Place in Northside Shopping Centre
not found
Gate 303
Place in Frankfurt am Main
not found
Frankfurt Airport (FRA)
Gate Z66
Place in ?? Shanghai
Modern Universe Business Plaza
DCU Sports Complex
Place in Prospect Square
Place in Dublin 7
Bust Stop No 44
not found
Tesco
Place in Dublin 1
DCU School of Computing
not found
DCU Restaurant
Chilli Banana
Hampstead Park
Place in Temple Bar
Ulster Bank
The Hub
Dublin Airport (DUB)
Place in ??? / Chaoyang
Place in ??? (Beijing)
Place in ??
Place in ??? (Yong He Gong Lama Temple)
not found
Place in ????
Place in ?????
Starbucks ???
??? McDonald's
Sosiaali - ja terveystoimi
not found
Kauppatori
K-supermarket
Pysï¿½kki 828
not found
Ravintola Tower
Tiia koti
not found
Place in Aviapoliksen suuralue
not found
Place in APN 1
Helsinki railway station
Place in Kluuvi
not found
Pub Varpu
Place in Ullanlinna
not found
Mulhuddart Community Centre
Razor's Barber Shop
Blanchardstown / Baile Bhlainsï¿½ir
not found
Tesco Express
Under Ildl
not found
Busï¿½ras
not found
Athlone Town Centre
Moate
Place in Dublin 11
not found
Place in Rotunda Maternity Hospital
not found
Woolshed Baa & Grill
Reed Specialist Recruitment
not found
Dublin Bus
Citizens Information
40D Bus Stop
Dublin Bus Stop No. 4522
not found
Citywest Shopping Centre
Uniphar
not found
Terminal 1
Butchery
Finglas Leisure Centre
Bus Stop 1624

In [12]:
len(latitude_df)

81

In [7]:
latitude_df=pd.DataFrame(latitude)
longitude_df =pd.DataFrame(latitude)
locations=locations[2:]
locations_found=[]

In [8]:
locs=df['location'].unique()
locs=pd.DataFrame(locs)
locs.columns=["locations"]

In [8]:
import plotly
plotly.offline.init_notebook_mode(connected=True)
lons = longitude
lats = latitude

 
data = [ dict(
        type = 'scattergeo',
        locationmode = 'Europe',
        lon = lons,
        lat = lats,
        text = locations_found,
        mode = 'markers',
        marker = dict(
            size = 8,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = False,
            symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            )))]

layout = dict(
        title = 'Locations visited by user 1 (there are some mistakes...)',
        colorbar = True,
        geo = dict(
            scope='europe',
            projection=dict( type='albers us' ),
            showland = True,
            landcolor = "rgb(250, 250, 250)",
            subunitcolor = "rgb(217, 217, 217)",
            countrycolor = "rgb(217, 217, 217)",
            countrywidth = 0.5,
            subunitwidth = 0.5
        ),
    )

fig = dict( data=data, layout=layout )
plotly.offline.iplot( fig, validate=False, filename='d3-airports' )

In [13]:
airports = [ dict(
        type = 'scattergeo',
        locationmode = 'Europe',
        lon = lons,
        lat = lats,
        hoverinfo = 'text',
        text = locations_found,
        mode = 'markers',
        marker = dict( 
            size=2, 
            color='rgb(255, 0, 0)',
            line = dict(
                width=3,
                color='rgba(68, 68, 68, 0)'
            )
        ))]


layout = dict(
        title = 'Feb. 2011 American Airline flight paths<br>(Hover for airport names)',
        showlegend = False, 
        geo = dict(
            scope='Europe',
            projection=dict( type='azimuthal equal area' ),
            showland = True,
            landcolor = 'rgb(243, 243, 243)',
            countrycolor = 'rgb(204, 204, 204)',
        ),
    )
    


fig = dict( data=data, layout=layout )
plotly.offline.iplot( fig, validate=False, filename='d3-airports' )